<div class="mainMenuSrchText">
    
Type the search term you want to find. Examples:
<ul class="unpadded">
<li>Italian cooking</li>
<li>The Appeal</li>
<li>tax and legislat*</li>
<li>(lunar or solar) and eclipse</li>
</ul>
<form method="get" target="_blank" action="http://archway.searchmobius.org/search/X?"enctype="multipart/form-data">
	

	
	<input type="text" name="SEARCH" id="search" placeholder="Search">


	<select id="searchscope" name="searchscope">
		<option value="1"> East Central College</option>
		<option value="2"> Jefferson College</option>
		<option value="3"> St. Charles Community College</option>
		<option value="4"> St. Louis Community College</option>
		<option value="6"> STLCC Forest Park</option>
		<option value="5"> STLCC Florissant Valley</option>
		<option value="8"> STLCC Meramec</option>
		<option value="11"> STLCC Wildwood</option>
		<option value="10"> STLCC Archives</option>
		<option value="7"> STLCC Highland Park</option>
		<option value="9"> St. Louis College of Pharmacy</option>
		<option selected="selected" value="12"> View Entire Collection</option>
	</select>
	<input type="hidden" name="SORT" value="D">


	<label for="formata"><input type="checkbox" name="m" id="m" value="a" /> Book<br /></label>

	<label for="format2"><input type="checkbox" name="m" id="m" value="2" /> eBook<br /></label>

	<label for="formatg"><input type="checkbox" name="m" id="m" value="g" /> DVD<br /></label>

	<label for="format6"><input type="checkbox" name="m" id="m" value="6" /> Blu-ray<br /></label>

	<label for="formaty"><input type="checkbox" name="m" id="m" value="y" /> Video Cassette<br /></label>

	<label for="format3"><input type="checkbox" name="m" id="m" value="3" /> Streaming Video<br /></label>

	<label for="formatj"><input type="checkbox" name="m" id="m" value="j" /> Audio - Music<br /></label>

	<label for="formati"><input type="checkbox" name="m" id="m" value="i" /> Book on CD<br /></label>

	<input type="submit" value="Submit">
</form>


</div>
